# Generated by Django 5.2.1 on 2025-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
