# Generated by Django 5.2.1 on 2025-05-10 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'content'], name='accounts_li_user_id_a4fd17_idx'),
        ),
    ]
