# Generated by Django 5.2.1 on 2025-05-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_like_accounts_li_user_id_a4fd17_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
