# Generated by Django 5.2.1 on 2025-05-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_content_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
